Reviewed OK.
4GeeksAcademy/spain-fs-pt-53-AB-AC-JO pull request #32
Opened 2024-03-26 18:29 UTC by abielsaf

2024-03-27 08:49 UTC, dsmora commented on src/front/js/pages/changePasswordForm.js
> +      alert('La contraseña nueva y confirmar contraseña nueva no coinciden.');
Para despues, poner aqui un toast. Mirad la libreria https://sweetalert2.github.io/#usage

2024-03-27 08:50 UTC, dsmora commented on src/front/js/pages/changePasswordForm.js
> +      alert("La visibilidad de tu perfil ha sido modificada correctamente.");
Para despues, poner aqui un toast. Mirad la libreria https://sweetalert2.github.io/#usage

2024-03-27 08:50 UTC, dsmora commented on src/front/js/pages/changePasswordForm.js
> +      alert("Uh oh, parece que ha ocurrido un error.");
Para despues, poner aqui un toast. Mirad la libreria https://sweetalert2.github.io/#usage

2024-03-27 08:50 UTC, dsmora commented on src/front/js/pages/modifyReview.js
> +      console.log(data.message);
remove this console.log

2024-03-27 08:50 UTC, dsmora commented on src/front/js/pages/modifyReview.js
> +      console.error("Error updating review:", error);
remove this console.log

2024-03-27 08:51 UTC, dsmora commented on src/front/js/pages/modifyReview.js
> +      alert("Vaya, ha ocurrido un error modificando tu review...");
Para despues, poner aqui un toast. Mirad la libreria https://sweetalert2.github.io/#usage

2024-03-27 08:51 UTC, dsmora commented on src/front/js/pages/profile.js
> +					console.error('Unauthorized');
remove console.error

2024-03-27 08:51 UTC, dsmora commented on src/front/js/pages/profile.js
> +					console.error('Error:', response.statusText);
remove console.error

2024-03-27 08:51 UTC, dsmora commented on src/front/js/pages/profile.js
> +			console.log('Current user reviews:', reviews);
remove console.log

2024-03-27 08:51 UTC, dsmora commented on src/front/js/pages/profile.js
> +			console.error('Error:', error);
remove console.error

2024-03-27 08:51 UTC, dsmora commented on src/front/js/pages/profile.js
> +			console.log(data.message);
remove console.log

2024-03-27 08:52 UTC, dsmora commented on src/front/js/pages/profile.js
> +			alert('La review ha sido eliminada!');
Para despues, poner aqui un toast. Mirad la libreria https://sweetalert2.github.io/#usage

2024-03-27 08:52 UTC, dsmora commented on src/front/js/pages/profile.js
> +			console.error(error);
remove console.error

2024-03-27 08:52 UTC, dsmora commented on src/front/js/pages/signup.js
> +            alert("Las contraseñas no coinciden.");
Para despues, poner aqui un toast. Mirad la libreria https://sweetalert2.github.io/#usage

2024-03-27 08:52 UTC, dsmora commented on src/front/js/store/flux.js
>  				console.log("Session loading getting token")
remove console.log

2024-03-27 08:52 UTC, dsmora commented on src/front/js/store/flux.js
>  				console.log("session ends")
remove console.log

2024-03-27 08:53 UTC, dsmora commented on src/front/js/store/flux.js
> +						alert("Se ha registrado correctamente");
Para despues, poner aqui un toast. Mirad la libreria https://sweetalert2.github.io/#usage

2024-03-27 08:53 UTC, dsmora commented on src/front/js/store/flux.js
>  					console.error('Error changing password:', error);
remove console.error

2024-03-27 08:53 UTC, dsmora commented on src/front/js/store/flux.js
>  			changeColor: (index, color) => {
eliminaria esto del changeColor, pero despues de la presentación

2024-03-27 08:54 UTC, dsmora commented on src/front/styles/about.css
> +/* .about {
borrar este codigo muerto

2024-03-27 08:55 UTC, dsmora commented on src/front/styles/reviewform.css
> +  /* background-image: linear-gradient(43deg, #8FBF9F 5%, #F18F01 30%, #c2baa6 100%); */
codigo muerto, el comentario

2024-03-27 08:55 UTC, dsmora commented on src/front/styles/textEffect.css
> +/* .circle-effect {
borrar codigo muerto

2024-03-27 08:57 UTC, dsmora requested changes
Hay varios comentarios, lo mas importante eliminar todos los console.log y console.error. Y eliminar todo lo que sea codigo comentado, no queremos que esto vaya al deploy. Como futura mejora que no meteria ahora sobre todo por no tocar funcionalidad, cambiar todos los alert por esto, https://sweetalert2.github.io/#usage visualmente es mas bonito y correcto.

2024-04-02 21:27 UTC, abielsaf commented on src/front/styles/textEffect.css
> +/* .circle-effect {
Removed

2024-04-02 21:27 UTC, abielsaf commented on src/front/styles/reviewform.css
> +  /* background-image: linear-gradient(43deg, #8FBF9F 5%, #F18F01 30%, #c2baa6 100%); */
Done

2024-04-02 21:30 UTC, abielsaf commented on src/front/styles/about.css
> +/* .about {
Removed.

2024-04-03 09:14 UTC, abielsaf commented on src/front/js/pages/changePasswordForm.js
> +      alert('La contraseña nueva y confirmar contraseña nueva no coinciden.');
Done, looks great!

2024-04-05 09:27 UTC, dsmora approved these changes

2024-04-05 09:27 UTC, merged